# Generated by Django 3.2 on 2021-07-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgalary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgalary',
            options={'verbose_name': 'ProductGalary', 'verbose_name_plural': 'Product Galary'},
        ),
    ]
