# Generated by Django 3.2 on 2021-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('cart_image', models.ImageField(blank=True, upload_to='categories/photos')),
            ],
            options={
                'verbose_name': 'catgory',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
