# Generated by Django 3.2.15 on 2022-10-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cart_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
